test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  access_key_id: <%= ENV["SPACES_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["SPACES_SECRET_KEY"] %>
  endpoint: <%= ENV["SPACES_ENDPOINT"] %>
  region: <%= ENV["SPACES_REGION"] %>
  bucket: <%= ENV["SPACES_BUCKET"] %>
  force_path_style: false
